### ISSUE TITLE
Crash on Ubuntu 18.04

### ISSUE THREAD

**Issue by amaccuish** [open-eid/qesteidutil#104]
Utility crashes when trying to read data

(gdb) run
Starting program: /usr/bin/qesteidutil 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeb1f7700 (LWP 15010)]
[New Thread 0x7fffe9d95700 (LWP 15011)]
QApplication: invalid style override passed, ignoring it.
libpng warning: iCCP: known incorrect sRGB profile
Enabling crashreporting "/tmp"
[New Thread 0x7fffe3fff700 (LWP 15014)]
Connecting to reader "ACS ACR 38U-CCID 00 00"
Connecting to reader "ACS ACR 38U-CCID 01 00"
Connecting to reader "ACS ACR 38U-CCID 01 00"
[New Thread 0x7fffe37fe700 (LWP 15016)]
Chache configuration serial: 64
Bundled configuration serial: 46

Thread 4 "QSmartCard" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe3fff700 (LWP 15014)]
0x00007ffff7625ca5 in sk_num () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
(gdb) backtrace
#0  0x00007ffff7625ca5 in sk_num () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#1  0x00007ffff766c1eb in X509V3_get_d2i () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#2  0x00005555555ce090 in ?? ()
#3  0x00005555555d0829 in ?? ()
#4  0x0000555555595fd7 in ?? ()
#5  0x00007ffff592516d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff7bbd6db in start_thread (arg=0x7fffe3fff700) at pthread_create.c:463
#7  0x00007ffff500388f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 

[crashReport.txt](https://github.com/open-eid/qesteidutil/files/2121425/crashReport.txt)

**Comment by metsma** [comment]
Is it compiled from source? Can you configure with cmake parameter -DCMAKE_BUILD_TYPE=Debug

**Comment by tomekit** [comment]
Happens to me as well on Ubuntu 18.04. Used the installer from: https://installer.id.ee/?lang=eng

**Comment by Counter178** [comment]
New Digidoc4 added all components to one. From the log it seems you still have old files from Digidoc3.
Digidoc4 client (which includes all funcionalities of Digidoc3, Utility and Crypto) is available to download via id.ee(supported Linux distributions Ubuntu 16.04 (LTS), 18.04 (LTS) (64bit)

**Comment by tomekit** [comment]
Right, there is chance that I've had it all installed previously, before I've upgraded Ubuntu from 16.04 to 18.04. It does look like the new installer may not replaced the older one correctly. I will try to remove everything and start from scratch. 
BTW @Counter178 what in my logs indicate that this is Digidoc3?

**Comment by Counter178** [comment]
@tomekit  "libpng warning: iCCP: known incorrect sRGB profile" indicates, that software has issues with profile version. 
Usually some files are either broken and need to be installed from scratch.
