### ISSUE TITLE
Clicking on View Certificate button triggers qesteidutil crash

### ISSUE THREAD

**Issue by Germano0** [open-eid/qesteidutil#82]
Clicking on View Certificate button (the one next to PIN1), triggers qesteidutil crash
OS: Fedora 26.

**GDB backtrace**
```
$ gdb qesteidutil 
GNU gdb (GDB) Fedora 8.0.1-30.fc26
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from qesteidutil...Reading symbols from /usr/lib/debug/usr/bin/qesteidutil.debug...done.
done.
(gdb) run
Starting program: /usr/bin/qesteidutil 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe53b2700 (LWP 25422)]
[New Thread 0x7fffd7afe700 (LWP 25423)]
libpng warning: iCCP: known incorrect sRGB profile
[New Thread 0x7fffcf102700 (LWP 25434)]
Detaching after fork from child process 25439.
[New Thread 0x7fffce901700 (LWP 25462)]
Failed to parse public key
[New Thread 0x7fffbffff700 (LWP 25463)]
[New Thread 0x7fffbf7fe700 (LWP 25464)]
[New Thread 0x7fffbeffd700 (LWP 25465)]
[New Thread 0x7fffbe7fc700 (LWP 25466)]
[New Thread 0x7fffbdffb700 (LWP 25467)]
[New Thread 0x7fffbd7fa700 (LWP 25468)]
[New Thread 0x7fffbcff9700 (LWP 25469)]

Thread 1 "qesteidutil" received signal SIGSEGV, Segmentation fault.
EVP_PKEY_base_id (pkey=pkey@entry=0x0) at crypto/evp/p_lib.c:385
385         return EVP_PKEY_type(pkey->type);
Missing separate debuginfos, use: dnf debuginfo-install compat-openssl10-1.0.2m-1.fc26.x86_64
(gdb) thread apply all backtrace

Thread 12 (Thread 0x7fffbcff9700 (LWP 25469)):
#0  0x00007ffff7bc490b in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555f93470) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555f93420, cond=0x555555f93448) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x555555f93448, mutex=mutex@entry=0x555555f93420) at pthread_cond_wait.c:655
#3  0x00007fffc745d14b in cnd_wait (mtx=0x555555f93420, cond=0x555555f93448) at ../../include/c11/threads_posix.h:159
#4  util_queue_thread_func (input=input@entry=0x555555f8ecd0) at u_queue.c:171
#5  0x00007fffc745d067 in impl_thrd_routine (p=<optimized out>) at ../../include/c11/threads_posix.h:87
#6  0x00007ffff7bbe36d in start_thread (arg=0x7fffbcff9700) at pthread_create.c:456
#7  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 11 (Thread 0x7fffbd7fa700 (LWP 25468)):
#0  0x00007ffff7bc490b in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555f93470) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555f93420, cond=0x555555f93448) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x555555f93448, mutex=mutex@entry=0x555555f93420) at pthread_cond_wait.c:655
#3  0x00007fffc745d14b in cnd_wait (mtx=0x555555f93420, cond=0x555555f93448) at ../../include/c11/threads_posix.h:159
#4  util_queue_thread_func (input=input@entry=0x555555f8ecd0) at u_queue.c:171
#5  0x00007fffc745d067 in impl_thrd_routine (p=<optimized out>) at ../../include/c11/threads_posix.h:87
#6  0x00007ffff7bbe36d in start_thread (arg=0x7fffbd7fa700) at pthread_create.c:456
#7  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 10 (Thread 0x7fffbdffb700 (LWP 25467)):
#0  0x00007ffff7bc490b in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555f93388) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
---Type <return> to continue, or q <return> to quit---
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555f93338, cond=0x555555f93360) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x555555f93360, mutex=mutex@entry=0x555555f93338) at pthread_cond_wait.c:655
#3  0x00007fffc745d14b in cnd_wait (mtx=0x555555f93338, cond=0x555555f93360) at ../../include/c11/threads_posix.h:159
#4  util_queue_thread_func (input=input@entry=0x555555f94440) at u_queue.c:171
#5  0x00007fffc745d067 in impl_thrd_routine (p=<optimized out>) at ../../include/c11/threads_posix.h:87
#6  0x00007ffff7bbe36d in start_thread (arg=0x7fffbdffb700) at pthread_create.c:456
#7  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 9 (Thread 0x7fffbe7fc700 (LWP 25466)):
#0  0x00007ffff7bc490b in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555f93388) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555f93338, cond=0x555555f93360) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x555555f93360, mutex=mutex@entry=0x555555f93338) at pthread_cond_wait.c:655
#3  0x00007fffc745d14b in cnd_wait (mtx=0x555555f93338, cond=0x555555f93360) at ../../include/c11/threads_posix.h:159
#4  util_queue_thread_func (input=input@entry=0x555555f94440) at u_queue.c:171
#5  0x00007fffc745d067 in impl_thrd_routine (p=<optimized out>) at ../../include/c11/threads_posix.h:87
#6  0x00007ffff7bbe36d in start_thread (arg=0x7fffbe7fc700) at pthread_create.c:456
#7  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 8 (Thread 0x7fffbeffd700 (LWP 25465)):
#0  0x00007ffff7bc490b in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555f93388) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555f93338, cond=0x555555f93360) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x555555f93360, mutex=mutex@entry=0x555555f93338) at pthread_cond_wait.c:655
#3  0x00007fffc745d14b in cnd_wait (mtx=0x555555f93338, cond=0x555555f93360) at ../../include/c11/threads_posix.h:159
---Type <return> to continue, or q <return> to quit---
#4  util_queue_thread_func (input=input@entry=0x555555f93910) at u_queue.c:171
#5  0x00007fffc745d067 in impl_thrd_routine (p=<optimized out>) at ../../include/c11/threads_posix.h:87
#6  0x00007ffff7bbe36d in start_thread (arg=0x7fffbeffd700) at pthread_create.c:456
#7  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 7 (Thread 0x7fffbf7fe700 (LWP 25464)):
#0  0x00007ffff7bc490b in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555f93e80) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555f93e30, cond=0x555555f93e58) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x555555f93e58, mutex=mutex@entry=0x555555f93e30) at pthread_cond_wait.c:655
#3  0x00007fffc745d14b in cnd_wait (mtx=0x555555f93e30, cond=0x555555f93e58) at ../../include/c11/threads_posix.h:159
#4  util_queue_thread_func (input=input@entry=0x555555f94440) at u_queue.c:171
#5  0x00007fffc745d067 in impl_thrd_routine (p=<optimized out>) at ../../include/c11/threads_posix.h:87
#6  0x00007ffff7bbe36d in start_thread (arg=0x7fffbf7fe700) at pthread_create.c:456
#7  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7fffbffff700 (LWP 25463)):
#0  0x00007ffff7bc490b in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555f8e698) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555f8e648, cond=0x555555f8e670) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x555555f8e670, mutex=mutex@entry=0x555555f8e648) at pthread_cond_wait.c:655
#3  0x00007fffc745d14b in cnd_wait (mtx=0x555555f8e648, cond=0x555555f8e670) at ../../include/c11/threads_posix.h:159
#4  util_queue_thread_func (input=input@entry=0x555555f8ecd0) at u_queue.c:171
#5  0x00007fffc745d067 in impl_thrd_routine (p=<optimized out>) at ../../include/c11/threads_posix.h:87
#6  0x00007ffff7bbe36d in start_thread (arg=0x7fffbffff700) at pthread_create.c:456
---Type <return> to continue, or q <return> to quit---
#7  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7fffce901700 (LWP 25462)):
#0  0x00007ffff5765d2d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff17be579 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x7fffc0003070, timeout=<optimized out>, context=0x7fffc0000990)
    at gmain.c:4271
#2  g_main_context_iterate (context=context@entry=0x7fffc0000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3967
#3  0x00007ffff17be68c in g_main_context_iteration (context=0x7fffc0000990, may_block=may_block@entry=1) at gmain.c:4033
#4  0x00007ffff658d47f in QEventDispatcherGlib::processEvents (this=0x7fffc00008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#5  0x00007ffff653b22a in QEventLoop::exec (this=this@entry=0x7fffce900cb0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#6  0x00007ffff638c99a in QThread::exec (this=<optimized out>) at thread/qthread.cpp:515
#7  0x00007ffff6390c72 in QThreadPrivate::start (arg=0x555555c7a080) at thread/qthread_unix.cpp:368
#8  0x00007ffff7bbe36d in start_thread (arg=0x7fffce901700) at pthread_create.c:456
#9  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 4 (Thread 0x7fffcf102700 (LWP 25434)):
#0  0x00007ffff7bc892d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff658cd6d in qt_nanosleep (amount=...) at kernel/qelapsedtimer_unix.cpp:195
#2  0x00005555555941b8 in QSmartCard::run (this=0x555555c8c9d0) at /usr/src/debug/qesteidutil-3.12.10/src/QSmartCard.cpp:666
#3  0x00007ffff6390c72 in QThreadPrivate::start (arg=0x555555c8c9d0) at thread/qthread_unix.cpp:368
#4  0x00007ffff7bbe36d in start_thread (arg=0x7fffcf102700) at pthread_create.c:456
#5  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

---Type <return> to continue, or q <return> to quit---
Thread 3 (Thread 0x7fffd7afe700 (LWP 25423)):
#0  0x00007ffff5765d2d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff17be579 in g_main_context_poll (priority=<optimized out>, n_fds=4, fds=0x7fffd0019080, timeout=<optimized out>, context=0x7fffd0000990)
    at gmain.c:4271
#2  g_main_context_iterate (context=context@entry=0x7fffd0000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3967
#3  0x00007ffff17be68c in g_main_context_iteration (context=0x7fffd0000990, may_block=may_block@entry=1) at gmain.c:4033
#4  0x00007ffff658d47f in QEventDispatcherGlib::processEvents (this=0x7fffd00008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#5  0x00007ffff653b22a in QEventLoop::exec (this=this@entry=0x7fffd7afdc70, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#6  0x00007ffff638c99a in QThread::exec (this=this@entry=0x7fffe81b1060 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>)
    at thread/qthread.cpp:515
#7  0x00007fffe813b689 in QDBusConnectionManager::run (this=0x7fffe81b1060 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>)
    at qdbusconnection.cpp:178
#8  0x00007ffff6390c72 in QThreadPrivate::start (arg=0x7fffe81b1060 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>)
    at thread/qthread_unix.cpp:368
#9  0x00007ffff7bbe36d in start_thread (arg=0x7fffd7afe700) at pthread_create.c:456
#10 0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7fffe53b2700 (LWP 25422)):
#0  0x00007ffff5765d2d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffef42cc97 in poll (__timeout=-1, __nfds=1, __fds=0x7fffe53b1bb0) at /usr/include/bits/poll2.h:46
#2  _xcb_conn_wait (c=c@entry=0x555555926a60, cond=cond@entry=0x555555926aa0, vector=vector@entry=0x0, count=count@entry=0x0) at xcb_conn.c:479
#3  0x00007fffef42ea8a in xcb_wait_for_event (c=0x555555926a60) at xcb_in.c:693
#4  0x00007fffe8432259 in QXcbEventReader::run (this=0x555555939a90) at qxcbconnection.cpp:1330
---Type <return> to continue, or q <return> to quit---
#5  0x00007ffff6390c72 in QThreadPrivate::start (arg=0x555555939a90) at thread/qthread_unix.cpp:368
#6  0x00007ffff7bbe36d in start_thread (arg=0x7fffe53b2700) at pthread_create.c:456
#7  0x00007ffff5771e1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7ffff7e09900 (LWP 25418)):
#0  EVP_PKEY_base_id (pkey=pkey@entry=0x0) at crypto/evp/p_lib.c:385
#1  0x00005555555caca4 in SslCertificate::publicKeyHex (this=this@entry=0x7fffffffc550) at /usr/src/debug/qesteidutil-3.12.10/common/SslCertificate.cpp:310
#2  0x00005555555b7422 in CertificateDialog::CertificateDialog (this=0x7fffffffc6e0, cert=..., parent=<optimized out>, removePath=<optimized out>)
    at /usr/src/debug/qesteidutil-3.12.10/common/CertificateWidget.cpp:123
#3  0x0000555555582609 in MainWindow::setDataPage (this=0x7fffffffd570, index=17) at /usr/src/debug/qesteidutil-3.12.10/src/MainWindow.cpp:571
#4  0x00007ffff6564d03 in QMetaObject::activate (sender=sender@entry=0x555555c97780, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, 
    argv=argv@entry=0x7fffffffc860) at kernel/qobject.cpp:3766
#5  0x00007ffff6565377 in QMetaObject::activate (sender=sender@entry=0x555555c97780, m=m@entry=0x7ffff728b220 <QButtonGroup::staticMetaObject>, 
    local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fffffffc860) at kernel/qobject.cpp:3628
#6  0x00007ffff6eab221 in QButtonGroup::buttonClicked (this=this@entry=0x555555c97780, _t1=<optimized out>) at .moc/moc_qbuttongroup.cpp:251
#7  0x00007ffff6ea6b81 in QAbstractButtonPrivate::emitClicked (this=this@entry=0x555555ae3830) at widgets/qabstractbutton.cpp:417
#8  0x00007ffff6ea7f3d in QAbstractButtonPrivate::click (this=0x555555ae3830) at widgets/qabstractbutton.cpp:407
#9  0x00007ffff6ea8134 in QAbstractButton::mouseReleaseEvent (this=0x555555ae36f0, e=0x7fffffffcd00) at widgets/qabstractbutton.cpp:1010
#10 0x00007ffff6df4428 in QWidget::event (this=0x555555ae36f0, event=0x7fffffffcd00) at kernel/qwidget.cpp:9198
#11 0x00007ffff6db5c9c in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555555ae36f0, e=0x7fffffffcd00) at kernel/qapplication.cpp:3722
#12 0x00007ffff6dbda3f in QApplication::notify (this=<optimized out>, receiver=0x555555ae36f0, e=0x7fffffffcd00) at kernel/qapplication.cpp:3198
#13 0x00007ffff653c4a7 in QCoreApplication::notifyInternal2 (receiver=0x555555ae36f0, event=0x7fffffffcd00) at kernel/qcoreapplication.cpp:1018
#14 0x00007ffff6dbca12 in QApplicationPrivate::sendMouseEvent (receiver=0x555555ae36f0, event=0x7fffffffcd00, alienWidget=0x555555ae36f0, 
---Type <return> to continue, or q <return> to quit---
    nativeWidget=0x7fffffffd570, buttonDown=<optimized out>, lastMouseReceiver=..., spontaneous=true) at ../../src/corelib/kernel/qcoreapplication.h:233
#15 0x00007ffff6e0f1db in QWidgetWindow::handleMouseEvent (this=0x555555dd05f0, event=0x7fffffffd0f0) at kernel/qwidgetwindow.cpp:621
#16 0x00007ffff6e1187f in QWidgetWindow::event (this=0x555555dd05f0, event=0x7fffffffd0f0) at kernel/qwidgetwindow.cpp:243
#17 0x00007ffff6db5c9c in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555555dd05f0, e=0x7fffffffd0f0) at kernel/qapplication.cpp:3722
#18 0x00007ffff6dbd4e4 in QApplication::notify (this=0x7fffffffd520, receiver=0x555555dd05f0, e=0x7fffffffd0f0) at kernel/qapplication.cpp:3481
#19 0x00007ffff653c4a7 in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x555555dd05f0, event=event@entry=0x7fffffffd0f0)
    at kernel/qcoreapplication.cpp:1018
#20 0x00007ffff6892b73 in QCoreApplication::sendSpontaneousEvent (event=0x7fffffffd0f0, receiver=0x555555dd05f0) at ../../src/corelib/kernel/qcoreapplication.h:236
#21 QGuiApplicationPrivate::processMouseEvent (e=0x555555ab8920) at kernel/qguiapplication.cpp:1949
#22 0x00007ffff6894755 in QGuiApplicationPrivate::processWindowSystemEvent (e=0x555555ab8920) at kernel/qguiapplication.cpp:1733
#23 0x00007ffff686e5cb in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at kernel/qwindowsysteminterface.cpp:939
#24 0x00007fffe8495010 in userEventSourceDispatch (source=<optimized out>) at qeventdispatcher_glib.cpp:77
#25 0x00007ffff17be257 in g_main_dispatch (context=0x7fffe00016f0) at gmain.c:3234
#26 g_main_context_dispatch (context=context@entry=0x7fffe00016f0) at gmain.c:3899
#27 0x00007ffff17be5f8 in g_main_context_iterate (context=context@entry=0x7fffe00016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at gmain.c:3972
#28 0x00007ffff17be68c in g_main_context_iteration (context=0x7fffe00016f0, may_block=may_block@entry=1) at gmain.c:4033
#29 0x00007ffff658d47f in QEventDispatcherGlib::processEvents (this=0x555555996040, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#30 0x00007ffff653b22a in QEventLoop::exec (this=this@entry=0x7fffffffd4a0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#31 0x00007ffff6543884 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1291
#32 0x0000555555577488 in main (argc=<optimized out>, argv=0x7fffffffd6d8) at /usr/src/debug/qesteidutil-3.12.10/src/main.cpp:79
```

**qesteidutil diagnostic info**
```
Locale: Italian / it_IT.UTF-8

Application version: 3.12.10.0 (64 bit)
OS: "Fedora release 26 (Twenty Six)"
CPU: AMD Phenom(tm) II X4 965 Processor
Kernel: Linux 4.13.13-200.fc26.x86_64 #1 SMP Wed Nov 15 15:46:36 UTC 2017 x86_64

Libraries:
qesteidutil (3.12.10)
openssl (1.1.0f)
pcsc-lite (1.8.22)
opensc (0.17.0)
QT (5.9.2)

Arguments: /usr/bin/qesteidutil
Library paths: /usr/lib64/qt5/plugins;/usr/bin
URLs:
BREAKPAD: https://cr.eesti.ee/
CONFIG_URL: https://id.eesti.ee/config.json

Central Configuration:

Smart Card service status: Running
Smart Card readers:
ACS ACR 38U-CCID 00 00 max APDU size 65536
Reader state: PRESENT, INUSE
ATR cold - 3BFA1800008031FE45FE654944202F20504B4903
ATR warm - 3BFE1800008031FE45803180664090A4162A00830F9000EF
ID - 38601270070


Browsers:
firefox (57.0)
```

**Comment by metsma** [comment]
Probably mixing openssl 1.0 and 1.1 versions

**Comment by Germano0** [comment]
No, openssl-1.1.0f-7.fc26.x86_64

**Comment by metsma** [comment]
Yeah but qt does not support openssl 1.1.
Qt 5.10 release in RC stage
https://github.com/qt/qtbase/blob/5.10.0/dist/changes-5.10.0#L383
You must link qesteidutil with same openssl as Qt uses

**Comment by Germano0** [comment]
On Fedora 27 the package works correctly. F27 has Qt compiled against OpenSSL 1.1
